# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'circles.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Circles(object):
    def setupUi(self, Circles):
        Circles.setObjectName("Circles")
        Circles.resize(640, 480)
        self.pushButton = QtWidgets.QPushButton(Circles)
        self.pushButton.setGeometry(QtCore.QRect(232, 10, 141, 61))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Circles)
        QtCore.QMetaObject.connectSlotsByName(Circles)

    def retranslateUi(self, Circles):
        _translate = QtCore.QCoreApplication.translate
        Circles.setWindowTitle(_translate("Circles", "Form"))
        self.pushButton.setText(_translate("Circles", "КНОПКА"))
